name: Deploy to Cloud Run

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  PORT: ${{ secrets.PORT }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/webscraping-app/webscraping-app
  SERVICE_NAME: webscraping-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f backend/Dockerfile.backend backend
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated